# Generated by Django 6.0.6 on 2026-06-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('production', '0002_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to='orders.order'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='production.productionstage'),
        ),
        migrations.AddField(
            model_name='materialestimate',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='stock.inventoryitem'),
        ),
        migrations.AddField(
            model_name='materialestimate',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimates', to='production.productionstage'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='material_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='production.productionstage'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['status'], name='stock_mater_status_7c4951_idx'),
        ),
    ]
