# Generated by Django 6.0.6 on 2026-06-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('trigger_event', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=6)),
                ('gateway_response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-sent_at'], name='notificatio_sent_at_cb23b4_idx')],
            },
        ),
    ]
