# Generated by Django 6.0.6 on 2026-06-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='order_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('item_description', models.TextField()),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRICE_REVIEW', 'Price Review'), ('OPS_QUEUE', 'Ops Queue'), ('IN_PRODUCTION', 'In Production'), ('WORKSHOP_COMPLETE', 'Workshop Complete'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='branches.branch')),
            ],
        ),
    ]
