# Generated by Django 6.0.6 on 2026-06-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('orders', '0002_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtransferrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchtransferrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchtransferrequest',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_transfers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_sales', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showroomitem',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showroom_items', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='showroomitem',
            name='parent_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='shop.showroomitem'),
        ),
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='shop.showroomitem'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='shop.showroomitem'),
        ),
        migrations.AddField(
            model_name='branchtransferrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_requests', to='shop.showroomitem'),
        ),
        migrations.AddIndex(
            model_name='showroomitem',
            index=models.Index(fields=['branch', 'status'], name='shop_showro_branch__7ef458_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomitem',
            index=models.Index(fields=['sku'], name='shop_showro_sku_afaa1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomitem',
            unique_together={('sku', 'branch')},
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-sold_at'], name='shop_sale_branch__ab7b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['is_active', 'expiry_date'], name='shop_reserv_is_acti_e4d103_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransferrequest',
            index=models.Index(fields=['status'], name='shop_branch_status_04bdb4_idx'),
        ),
    ]
