# Generated by Django 6.0.6 on 2026-06-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='productionstage',
            index=models.Index(fields=['assigned_technician', 'status'], name='production__assigne_fa9081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionstage',
            unique_together={('order', 'sequence_number')},
        ),
    ]
